version: '3.4'

services:
  despesas-python:
    image: alexfariakof/despesas-pessoais-python-img
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
      - 5000:5000
      - 5002:5002